### PR TITLE
feat: Buddhism theme

### PR DESCRIPTION
**Pull request by ittipatken**

### CODE REVIEW

**Comment by keenthekeen** [comment]
It might make the app look like Dharma E-Learning website...

**Comment by ittipatken** [comment]
@Punpunyawish any opinions?

**Comment by ittipatken** [comment]
> It might make the app look like Dharma E-Learning website...

We have Christianity-related themes, so I thought we should have other religions too. If the artwork is not favorable, I can notify the artist.

**Comment by Punpunyawish** [comment]
I think it's fine; just a seasonal holiday's theme.

**Comment by ittipatken** [comment]
I talked with the artist. She decided to remove monk illustrations to avoid conflicts.

**Pull request merged**
