### PR TITLE
ci: add Docker

### PR DESCRIPTION
**Pull request by ittipatken**

### CODE REVIEW

**Comment by keenthekeen** [comment]
I haven’t had a chance to test it yet, but it seems that configuring Nginx to respond to all paths with index.html might be necessary.

See https://github.com/docchula/el-player?tab=readme-ov-file#deployment .

**Comment by ittipatken** [comment]
~~I tested it on my local desktop and it works fine. Nginx should probably be configured, though.~~
I think I tested a wrong image. I will add the configuration file.

**Comment by keenthekeen** [comment]
Done.

**Comment by ittipatken** [comment]
Thank you 🙇‍♂️

**Pull request merged**
